name: project_test
description: A new Flutter project.
publish_to: 'none' # This prevents the package from being accidentally published to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/easy_transfer.png
    - assets/images/tailored_budgeting.png
    - assets/images/logo.png
    - assets/images/wallet_security.png
